### ISSUE TITLE
Antivirus false positive

### ISSUE THREAD

**Issue by Sylent4** [Kaiddd/RobloxClientOptimizer2#2]

**Comment by Kaiddd** [comment]
There's no malware, it's open source software, and I'm the original author. RCO is also discontinued in favor of RFO. Therefore no reason to report false positives to antivirus companies, therefore invalid issue, closed, thank you for your conerns.

**Comment by Sylent4** [comment]
Hey, I downloaded this optimizer since my pc has trouble playing Roblox and
I needed the extra performance to test my games. As soon as I download it,
Windows Defender reports it as a Trojan and it clearly shows a few files
with Trojan in their name. You very clearly injected multiple Trojans into
this zip file to steal people’s data. Very disappointing. Also, you can’t
just say “well Windows Defender isn’t trustworthy” because it’s literally
the best antivirus possible. I’ve already reported your repo to GitHub.

**Comment by Kaiddd** [comment]
Windows defender is very trustworthy, but every antivirus has false positives. This is safe software, however is discontinued and not recommended for use anyways.

**Comment by Kaiddd** [comment]
If you don't trust it, just build the software from source.

If you're coming from the sharkblox video, feel free to pause it at a certain timestamp and you'll see my github user somewhere lol, I am the old dev.

**Comment by Kaiddd** [comment]
Or, if you're just worried about the executables, feel free to run them through IDA and analyze the files for anything malicious, you won't find anything bad

**Comment by Kaiddd** [comment]
Also, I own both of the original RCO repos that were transfered to me by L8X

See here:
https://github.com/Kaiddd/roblox-client-optimizer-originalrepo
https://github.com/Kaiddd/Roblox-Client-Optimizer

Both have tons of forks and stars from real github accounts

This is just an archive of the source for version 2.0

I will also be archiving this repo as it is archived, and forgot to archive it beforehand.
